In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("iris.csv")
df.head()


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [7]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
df.Species.value_counts()

Iris-virginica     50
Iris-versicolor    50
Iris-setosa        50
Name: Species, dtype: int64

In [9]:
len(df)

150

In [10]:
df['Species_label'], _ = pd.factorize(df['Species'])
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [27]:
df.Species_label.head()

0    0
1    0
2    0
3    0
4    0
Name: species_label, dtype: int64

In [9]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [10]:
df['Species'] = df['Species'].map({"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":2}).astype(int)

In [12]:
df = df.drop(['Id'],axis = 1)

In [13]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.9           3.0            1.4           0.2        0
2            4.7           3.2            1.3           0.2        0
3            4.6           3.1            1.5           0.2        0
4            5.0           3.6            1.4           0.2        0

In [32]:
X = df.drop(['Species'],axis=1)
y = df['Species']

In [15]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [16]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [17]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Species, dtype: int32

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.22, random_state=42)

In [20]:
X_train.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
146            6.3           2.5            5.0           1.9
51             6.4           3.2            4.5           1.5
27             5.2           3.5            1.5           0.2

In [21]:
X_test.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73             6.1           2.8            4.7           1.2
18             5.7           3.8            1.7           0.3
118            7.7           2.6            6.9           2.3
78             6.0           2.9            4.5           1.5
76             6.8           2.8            4.8           1.4

In [22]:
y_train.head()

11     0
42     0
146    2
51     1
27     0
Name: Species, dtype: int32

In [23]:
y_test.head()

73     1
18     0
118    2
78     1
76     1
Name: Species, dtype: int32

In [24]:
from sklearn.tree import DecisionTreeClassifier
reg = DecisionTreeClassifier()
reg.fit(X_train,y_train)

DecisionTreeClassifier()

In [25]:
y_train_pred = reg.predict(X_train)

In [26]:
y_train_pred[:10]

array([0, 0, 2, 1, 0, 0, 0, 2, 1, 1])

In [27]:
y_train[:10]

11     0
42     0
146    2
51     1
27     0
4      0
32     0
142    2
85     1
86     1
Name: Species, dtype: int32

In [28]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [29]:
accuracy_score(y_train,y_train_pred)

1.0

In [30]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       1.00      1.00      1.00        40
           2       1.00      1.00      1.00        39

    accuracy                           1.00       117
   macro avg       1.00      1.00      1.00       117
weighted avg       1.00      1.00      1.00       117



In [31]:
confusion_matrix(y_train,y_train_pred)

array([[38,  0,  0],
       [ 0, 40,  0],
       [ 0,  0, 39]], dtype=int64)

In [32]:
y_test_pred = reg.predict(X_test)
y_test_pred[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1])

In [33]:
y_test[:10]

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
Name: Species, dtype: int32

In [34]:
accuracy_score(y_test,y_test_pred)

1.0

In [35]:
confusion_matrix(y_test,y_test_pred)

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 11]], dtype=int64)

In [36]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        11

    accuracy                           1.00        33
   macro avg       1.00      1.00      1.00        33
weighted avg       1.00      1.00      1.00        33



In [56]:
# lets check with the hypeparameter tuning technique using GridsearchCV

### GridsearchCV

In [57]:
from sklearn.model_selection import GridSearchCV

In [58]:
model = DecisionTreeClassifier()


In [59]:
parameters = {
    
    'criterion':['gini','entropy'],
    'max_depth':[2,3,4,5,6,7,10,11,14,20,25,30],
    'min_samples_split':[2,3,4,5,6],
    'min_samples_leaf':[2,3,4,5],
    'presort':[True,False],
    'class_weight':['balanced',None]
    }


grid_model = GridSearchCV(estimator=model,
                          param_grid=parameters,
                          scoring='accuracy',
                          cv=10)

grid_model1 = grid_model.fit(X_train,y_train)

In [60]:
grid_model1.best_params_

{'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': 4,
 'min_samples_leaf': 3,
 'min_samples_split': 2,
 'presort': True}

In [64]:
reg1 = DecisionTreeClassifier(class_weight='balanced',criterion='gini',max_depth=4,min_samples_leaf=3,
                              min_samples_split=2,presort=True)
reg1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight='balanced', criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=True,
                       random_state=None, splitter='best')

In [68]:
y_train_pred1 = reg1.predict(X_train)
y_train_pred1[:10]


array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [69]:
y_train_pred[:10]

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [70]:
accuracy_score(y_train,y_train_pred1)

0.96

In [71]:
confusion_matrix(y_train,y_train_pred1)

array([[31,  0,  0],
       [ 0, 32,  3],
       [ 0,  1, 33]], dtype=int64)

In [72]:
print(classification_report(y_train,y_train_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       0.97      0.91      0.94        35
           2       0.92      0.97      0.94        34

    accuracy                           0.96       100
   macro avg       0.96      0.96      0.96       100
weighted avg       0.96      0.96      0.96       100



In [73]:
y_test_pred1 = reg1.predict(X_test)

In [74]:
y_test_pred1[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1], dtype=int64)

In [75]:
accuracy_score(y_test,y_test_pred1)

1.0

In [76]:
confusion_matrix(y_test,y_test_pred1)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 16]], dtype=int64)

In [77]:
print(classification_report(y_test,y_test_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

